### ISSUE TITLE
Error following DSM and SSS update

### ISSUE THREAD

**Issue by Charles-Em** [djdd87/SynoAI#225]
Hello,

I recently updated DSM to 7.2 and SSS to 9.2.1-11380 and since then, I get the following error : failed to get a snapshot

Does that seem familiar?

Regards,
Charles

**Comment by de1et3d** [comment]
@Charles-Em please have a look at the release notes: https://www.synology.com/ru-ru/releaseNote/DSM and this article: https://kb.synology.com/en-us/Surveillance/tutorial/What_functions_will_be_adjusted_due_to_the_change_in_support_for_H265_on_Surveillance_Station_and_DS_cam 
The issue caused by the recent changes from Synology. As a workaround you can switch your cameras to use H.264/H.264+

**Comment by Charles-Em** [comment]
Thanks for the links.

Ok I read that and adjusted my configuration.
Luckily my camera model is now in SSS and I switched from ONVIF to the supported cam. Because well, I don't have H264.
Seems the snapshot doesn't work on H265+, but it does with H265 after also tweeking a single push instead of 2 (that part sucks, I liked having 2 snapshots, I will see if I can get this to work again somehow)
