### ISSUE TITLE
Just curious if its possible to put the steps in blueprint on home assistant for setting it up to notify 

### ISSUE THREAD

**Issue by Neogx** [djdd87/SynoAI#50]
I got synoAI working beautifully but for the life of me can't set up an Automation in home assistant to get a notification with a picture send to my phone . ii  was thinking if someone could put the steps into a blueprint then everyone can easily just import the core steps to their home assistant

**Comment by djdd87** [comment]
Sorry, I don't use HA much any more. I didn't even know there was such a thing as blueprints! If you work it out, feel free to reply back here and I can add it to the readme.

**Comment by JohannCR** [comment]
Hi,
Like this one ?
https://community.home-assistant.io/t/send-camera-snapshot-notification-on-motion/254565

**Comment by djdd87** [comment]
@Neogx did you manage to create one? If so I'll add it to the wiki. If not, I'll close this ticket off.

**Comment by Neogx** [comment]
Naw i wish I was able to but  just gave up in the end

**Comment by JohannCR** [comment]
For my part I don't use HA notifications because I found it adds some delay... Using Pushbullet directly in synoAI config (still got some delay though but more reasonable).
But I found useful to add some picture-entity in HA dashboard to see at a glance the last snapshot. Useful for less important detections for which I do not need a notification^^
Doesn't help much this topic I guess 😂

**Comment by djdd87** [comment]
> Naw i wish I was able to but just gave up in the end. Before you close this just curious what method you use to notify you

I use Telegram personally. I don't use HA for notifications as they're slower in comparison as it's _another_ layer between the camera detection and the notification.
